name: Fetch updated list of skilled sponsor companies
on: 
  push:
    branches: [ main ]
jobs:
  get-latesturl:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching details from GOV Api..
        id: get_details
        uses: octokit/request-action@v2.x
        with:
          route: GET ${{ secrets.GOV_UK_SPONSOR_LINK }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "${{ fromJson(steps.get_details.outputs.data).details.attachments[0].url }}"
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download latest CSV from the link
        run: |-
          wget ${{ fromJson(steps.get_details.outputs.data).details.attachments[0].url }} -O ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }}
      - name: Commit all changes
        id: commit
        run: |-
          git config user.name "Strange Supreme"
          git config user.email "actions@github.com"
          git add --all
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Updated lastest CSV" -a
             echo "::set-output name=push::true"
          fi
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
  
